name: bwind
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  easy_localization: null
  file_picker: ^6.1.1
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  flutter_rating_bar: null
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^4.2.1
  flutter_spinkit: ^5.2.0
  fluttertoast: null
  freezed_annotation: ^2.4.1
  go_router: ^11.1.3
  google_fonts: ^6.1.0
  google_sign_in: null
  hive: ^2.2.3
  image_picker: ^1.0.7
  intl: null
  json_annotation: ^4.8.1
  light_modal_bottom_sheet: null
  loggy: ^2.0.3
  lottie: ^3.0.0
  mailer: null
  mask_text_input_formatter: null
  month_picker_dialog: null
  path_provider: ^2.1.2
  pretty_animated_buttons: ^0.0.1
  riverpod_annotation: ^2.3.4
  sentry_flutter: ^7.19.0
  shared_preferences: null
  syncfusion_flutter_pdf: ^24.2.4
  syncfusion_flutter_pdfviewer: ^24.2.5
  url_launcher: null
  uuid: ^4.3.3

dev_dependencies:

  build_runner: ^2.4.8

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translates/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
